services:
  nginx:
    build: ./nginx
    ports:
      - "${PUBLIC_WEB_HOST_PORT}:80"
    networks:
      public_net:
        ipv4_address: ${PUBLIC_WEB_IP}
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route replace ${SERVICE_SUBNET} via ${PUBLIC_SERVICE_FW_PUBLIC_IP} && envsubst '$$PUBLIC_PROBE_IP $$PUBLIC_PROBE_PORT $$SERVICE_API_IP $$SERVICE_API_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    environment:
      - PUBLIC_PROBE_IP=${PUBLIC_PROBE_IP}
      - PUBLIC_PROBE_PORT=${PUBLIC_PROBE_PORT}
      - SERVICE_API_IP=${SERVICE_API_IP}
      - SERVICE_API_PORT=${SERVICE_API_PORT}
    depends_on:
      - probe

  probe:
    build: ./probe
    container_name: public-probe
    hostname: public-probe
    networks:
      public_net:
        ipv4_address: ${PUBLIC_PROBE_IP}
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route replace ${SERVICE_SUBNET} via ${PUBLIC_SERVICE_FW_PUBLIC_IP} && npm start"
    environment:
      - ZONE_NAME=public
      - PORT=${PUBLIC_PROBE_PORT}

networks:
  public_net:
    external: true
    name: ${PUBLIC_NET_NAME}
